### ISSUE TITLE
Decimal128 is not compatible type

### ISSUE THREAD

**Issue by vinodprathipati** [SoftInstigate/restheart#184]
We are getting the following exception when we have type DecimalType in our BSON.

org.bson.BsonSerializationException: Detected unknown BSON type "\x13" for fieldname "field_0". Are you using the latest driver version?
        at org.bson.BsonBinaryReader.readBsonType(BsonBinaryReader.java:94)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:82)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
        at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
        at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)

**Comment by mkjsix** [comment]
Which version of RESTHeart and MongoDB are you using?

**Comment by vinodprathipati** [comment]
I am using Restheart 3 and MongoDB 3.4

**Comment by vinodprathipati** [comment]
I see inside manifest file, it was specified to use mongo-java-driver-3.3.0.jar. How to change this?

**Comment by mkjsix** [comment]
The 3.1.0-SNAPSHOT uses the very latest 3.4.1 Java driver. You can build it by yourself or download the latest build from the Maven repository:

https://oss.sonatype.org/service/local/repositories/snapshots/content/org/restheart/restheart/3.1.0-SNAPSHOT/restheart-3.1.0-20170210.180120-18.zip

**Comment by vinodprathipati** [comment]
yes.. it worked.
