### ISSUE TITLE
Windows Docker Issue

### ISSUE THREAD

**Issue by andrejpodgorsek** [SoftInstigate/restheart#210]
I used cmder and build.sh succedded to build the maven build... then the next step failed:

> λ docker-compose up -d && docker-compose logs -f
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 88, in main
  File "compose\cli\main.py", line 140, in perform_command
  File "compose\cli\main.py", line 900, in up
  File "compose\project.py", line 385, in up
  File "compose\project.py", line 590, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 73, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 179, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'Das System kann die angegebene Datei nicht finden.')
Failed to execute script docker-compose

**Comment by mkjsix** [comment]
Hi,
It's seems to be an issue related to your installation of docker-compose, the error message 'Das System kann die angegebene Datei nicht finden.' says that the docker command is not able to find a file.

I suggest to check if docker is actually running properly on your machine and, in case, re-install it.

See: https://github.com/laradock/laradock/issues/565

**Comment by ArminVieweg** [comment]
Hey. I've got the same issue, when I run docker-compose on bash, which is not prepared by start.sh script. 

When I try to execute the start.sh script in .bash_profile I'll get this error when starting bash:

> Docker Machine is not installed. Please re-run the Toolbox Installer and try again.
> Looks like something went wrong in step ´Looking for vboxmanage.exe´... Press any key to continue...

This message does not occure when I change the directory to destination where I've installed Docker Toolbox before executing start.sh.

**Comment by mkjsix** [comment]
@ArminVieweg it looks like a path issue, have you tried the native Docker for Windows?

https://docs.docker.com/docker-for-windows/install/

AFAIK, this is not the same as installing the Toolbox, the underlying technologies are different.

**Comment by ArminVieweg** [comment]
@mkjsix Yeah right. This requires Hyper-V, which I dont want to use, because then Virtual Box is not working. And I am very very new to Docker at all^^

However, I've created an alias in my .bashrc:

     alias docker-bash='export curdir=$(pwd) && cd /c/Dev/Tools/DockerToolbox/ && start.sh "" && cd $curdir'

Now, when enter `docker-bash` the start.sh script is executed and it returns to my previous working directory. Then `docker-compose` also works seamlessly.

**Comment by mkjsix** [comment]
This could be relevant in your case: https://github.com/docker/for-win/issues/316

**Comment by ArminVieweg** [comment]
Very cool! Thanks @mkjsix 

When I perform a `docker-machine env` I get this output:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\Me\.docker\machine\machin
export DOCKER_MACHINE_NAME="default"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Dev\Tools\DockerToolbox\docker-machine.exe" env)
```
When I perform the eval command, it works!

**Comment by mkjsix** [comment]
Closing this now. Feel free to re-open in case.
