### ISSUE TITLE
No HAL browser in 3.0.1

### ISSUE THREAD

**Issue by robshep** [SoftInstigate/restheart#211]
Hi, I did the following...

```
https://raw.githubusercontent.com/SoftInstigate/restheart/master/Docker/docker-compose.yml
export RELEASE=3.0.1
docker-compose up
```

and saw

```
restheart    | 09:20:40.928 [main] INFO  org.restheart.Bootstrapper - MongoDB connection pool initialized
restheart    | 09:20:40.929 [main] INFO  org.restheart.Bootstrapper - MongoDB version 3.2.13
restheart    | 09:20:41.134 [main] INFO  org.restheart.Bootstrapper - Token based authentication enabled with token TTL 15 minutes
restheart    | 09:20:41.154 [main] INFO  org.restheart.Bootstrapper - HTTPS listener bound at 0.0.0.0:4443
restheart    | 09:20:41.154 [main] INFO  org.restheart.Bootstrapper - HTTP listener bound at 0.0.0.0:8080
restheart    | 09:20:41.157 [main] INFO  org.restheart.Bootstrapper - Local cache for db and collection properties enabled with TTL 1000 msecs
restheart    | 09:20:41.157 [main] INFO  org.restheart.Bootstrapper - Local cache for schema stores enabled  with TTL 60000 msecs
restheart    | 09:20:41.368 [main] INFO  org.restheart.Bootstrapper - URL / bound to MongoDB resource *
restheart    | 09:20:41.372 [main] WARN  o.restheart.utils.ResourcesExtractor - no resource to extract from path  browser
restheart    | 09:20:41.377 [main] ERROR org.restheart.Bootstrapper - Error extracting embedded static resource browser
restheart    | java.lang.IllegalStateException: no resource to extract from path browser
restheart    | 	at org.restheart.utils.ResourcesExtractor.extract(ResourcesExtractor.java:85)
restheart    | 	at org.restheart.Bootstrapper.lambda$pipeStaticResourcesHandlers$2(Bootstrapper.java:796)
restheart    | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
restheart    | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
restheart    | 	at org.restheart.Bootstrapper.pipeStaticResourcesHandlers(Bootstrapper.java:765)
restheart    | 	at org.restheart.Bootstrapper.getHandlersPipe(Bootstrapper.java:705)
restheart    | 	at org.restheart.Bootstrapper.startCoreSystem(Bootstrapper.java:576)
restheart    | 	at org.restheart.Bootstrapper.startServer(Bootstrapper.java:376)
restheart    | 	at org.restheart.Bootstrapper.main(Bootstrapper.java:135)
restheart    | 09:20:41.377 [main] ERROR org.restheart.Bootstrapper - **** Have you downloaded the HAL Browser submodule before building?
restheart    | 09:20:41.377 [main] ERROR org.restheart.Bootstrapper - **** To fix this, run: $ git submodule update --init --recursive
```

and at `http://localhost:8080/browser`

    {"http status code":404,"http status description":"Not Found","message":"Db 'browser' does not exist"}

**Comment by mkjsix** [comment]
Hi, the last two lines of your log are telling the source of your problem.

Besides, the latest stable version of RH is 3.0.3: are you building the container manually? Why don't you just `docker pull softinstigate/restheart:3.0.3` instead?

If for some reason you need to build the image by yourself, then have a look at the script build.sh into Docker folder.

**Comment by robshep** [comment]
Sorry,

I did not check the latest version.  I was just copying the process from

https://hub.docker.com/r/softinstigate/restheart/

which mentions 3.0.1

I can confirm that the halbrowser is baked into the stock 3.0.3 image

```restheart    | 09:52:15.735 [main] INFO  org.restheart.Bootstrapper - Embedded static resources browser extracted in /tmp/restheart-4025484141650419650
restheart    | 09:52:15.761 [main] INFO  org.restheart.Bootstrapper - URL /browser bound to static resources /tmp/restheart-4025484141650419650.
```

Thanks
