### ISSUE TITLE
error right away with no change to default setting

### ISSUE THREAD

**Issue by pdemilly** [SoftInstigate/restheart#26]
Not sure why. Looks like a security exception but my mongodb has no security set

java.lang.NullPointerException: null
	at org.restheart.security.handlers.ChallengingSecurityHandler.handleRequest(ChallengingSecurityHandler.java:48) ~[restheart.jar:0.10.1]
	at org.restheart.security.handlers.SecurityHandler.handleRequest(SecurityHandler.java:60) ~[restheart.jar:0.10.1]
	at org.restheart.handlers.injectors.BodyInjectorHandler.handleRequest(BodyInjectorHandler.java:80) ~[restheart.jar:0.10.1]
	at org.restheart.handlers.OptionsHandler.handleRequest(OptionsHandler.java:58) ~[restheart.jar:0.10.1]
	at org.restheart.handlers.injectors.RequestContextInjectorHandler.handleRequest(RequestContextInjectorHandler.java:240) ~[restheart.jar:0.10.1]
	at org.restheart.security.handlers.CORSHandler.handleRequest(CORSHandler.java:84) ~[restheart.jar:0.10.1]
	at org.restheart.handlers.PipedHttpHandler.handleRequest(PipedHttpHandler.java:86) ~[restheart.jar:0.10.1]
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:56) ~[restheart.jar:0.10.1]
	at io.undertow.server.handlers.HttpContinueAcceptingHandler.handleRequest(HttpContinueAcceptingHandler.java:78) ~[restheart.jar:0.10.1]
	at org.restheart.handlers.ErrorHandler.handleRequest(ErrorHandler.java:50) ~[restheart.jar:0.10.1]
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:66) [restheart.jar:0.10.1]
	at org.restheart.handlers.GzipEncodingHandler.handleRequest(GzipEncodingHandler.java:65) [restheart.jar:0.10.1]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) [restheart.jar:0.10.1]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:764) [restheart.jar:0.10.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by ujibang** [comment]
fixed in development branch.

thanks

**Comment by mkjsix** [comment]
Fix is also available in latest 0.10.2 release.
https://github.com/SoftInstigate/restheart/releases/tag/0.10.2
