### ISSUE TITLE
Azure JWT validation

### ISSUE THREAD

**Issue by aguarino77** [SoftInstigate/restheart#384]
I would like to use the Azure JWT issued by the Azure Active Directory to authenticate users in restheart.
I have set the following configuration in my restheart.yml file

```
jwtAuthenticationMechanism:
    enabled: true
    algorithm: RSA256
    key: jibNbkFSSbmxPYrN9CFqRk4K4gw
    base64Encoded: true
    usernameClaim: preferred_username
    rolesClaim: roles
    fixedRoles:
#      - admin
    issuer: https://login.microsoftonline.com/HIDDENONPURPOSE/v2.0
    audience: HIDDENONPURPOSE
``` 

but on startup I get the following error:

```
10:21:50.475 [main] ERROR org.restheart.plugins.PluginsFactory - Error injecting dependency to AuthMechanism jwtAuthenticationMechanism: Empty input
 java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: org.restheart.ConfigurationException: wrong JWT configuration, cannot setup algorithm
	at org.restheart.security.plugins.mechanisms.JwtAuthenticationMechanism.init(JwtAuthenticationMechanism.java:104)
Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
Caused by: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:111)

```
what's wrong?

**Comment by ujibang** [comment]
I tried your configuration and get

CertificateException: Could not parse certificate: java.io.IOException: Empty input

The key is invalid. I suspect you are using the public key, you need the private key!

**Comment by aguarino77** [comment]
Thank you. It works. 
Might help others: 
- base64Encoded: false
- you can get the Azure AD public key by polling https://login.microsoftonline.com/{TENANT}/discovery/keys and selecting the `x5c` item that has the same `kid` as your tokens
